keyform/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from django.contrib.auth.views import login, logout_then_login
from keyform import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^table.php$', RedirectView.as_view(pattern_name='home', permanent=True)),
    url(r'^contact$', views.ContactView.as_view(), name='contact'),
    url(r'^edit-contact/(?P<pk>\d+)$', views.EditContactView.as_view(), name='edit-contact'),
    url(r'^create-contact$', views.NewContactView.as_view(), name='create-contact'),
    url(r'^edit-request/(?P<pk>\d+)$', views.RequestView.as_view(), name='edit-request'),
    url(r'^create$', views.KeyRequest.as_view(), name='create'),
    url(r'^add-comment$', views.RequestCommentView.as_view(), name='add-comment'),
    url(r'^login$', login, name='login', kwargs={'template_name': 'keyform/login.html'}),
    url(r'^logout$', logout_then_login, name='logout'),
]

keyformproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('keyform.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

keyform/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.core.validators import MinValueValidator
from decimal import Decimal
from django.core.validators import RegexValidator

class BuildingManager(models.Manager):
    def get_queryset(self):
        return super(BuildingManager, self).get_queryset().filter(deleted=False)

class Building(models.Model):
    name = models.CharField(max_length=256)
    deleted = models.BooleanField(default=False)
    objects = BuildingManager()
    all_buildings = models.Manager()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

class Status(models.Model):

    name = models.CharField(max_length=32)
    order = models.IntegerField()
    visible = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = _('Statuses')
        ordering = ['order']

class RequestManager(models.Manager):
    def get_queryset(self):
        return super(RequestManager, self).get_queryset().filter(status__visible=True)

class Request(models.Model):

    REQUEST_TYPES = (
        ('dk', _('Damaged Key')),
        ('lk', _('Lost/Stolen Key')),
        ('sk', _('Staff File Key')),
    )

    PAYMENT_TYPES = (
        ('ca', _('Cash')),
        ('ch', _('Check')),
        ('na', _('Not Applicable')),
    )

    objects = models.Manager()
    active_objects = RequestManager()

    bpn_validator = RegexValidator('[mM8]\d{8}', _("Bearpass number must start with an 'M,' 'm,' or '8,' and followed by eight digits."))

    building = models.ForeignKey(Building)
    student_name = models.CharField(max_length=128, blank=True)
    reason_for_request = models.CharField(max_length=2, choices=REQUEST_TYPES, verbose_name=_("Request for:"))
    amt_received = models.DecimalField(max_digits=7, decimal_places=2, default=0, blank=True, verbose_name= _('Amount received'), validators=[MinValueValidator(Decimal('0.00'))],
        help_text=_('Core Change/Reprogram Fob Charge = $50, Room Key/Fob = $10, Mailbox Key = $10, Monroe Mailbox Key = $25'))
    payment_method = models.CharField(max_length=2, choices=PAYMENT_TYPES)
    charge_amount = models.DecimalField(max_digits=7, default=0, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))], verbose_name=_("Bill to Account:"))
    staff = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('Staff member completing request'))
    bpn = models.CharField(max_length=9, verbose_name=_('M-Number'), validators=[bpn_validator], blank=True)
    created_timestamp = models.DateTimeField(default=now, blank=True)
    charged_on_rcr = models.BooleanField(default=False, verbose_name=_('Charged on RCR'))
    status = models.ForeignKey(Status, related_name="status")
    previous_status = models.ForeignKey(Status, related_name="previous_status")
    locksmith_email_sent = models.BooleanField(default=False)
    updated = models.BooleanField(default=True)

    def core_number_list(self):
        return [kd.core_number for kd in self.keydata_set.all() if kd.core_number]

    def room_number_list(self):
        return [kd.room_number for kd in self.keydata_set.all() if kd.room_number]

    def __str__(self):
        return str(self.get_reason_for_request_display()) + " " + str(self.created_timestamp)

    class Meta:
        ordering = ['-created_timestamp']

class KeyType(models.Model):
    name = models.CharField(max_length=128)
    hide_core_number = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class KeyData(models.Model):
    request = models.ForeignKey(Request)
    core_number = models.CharField(max_length=35, verbose_name=_('New Core Number'), blank=True,
        help_text=_('Use a comma to separate the list of cores (if suite style).'))
    key_type = models.ForeignKey(KeyType, null=True)
    room_number = models.CharField(max_length=42)
    key_number = models.CharField(max_length=24, verbose_name=_('Lost/Stolen/Damaged Key Number'))
    quantity = models.IntegerField(validators=[MinValueValidator(0)],
        help_text=_("If you don't need to order more keys because there are enough already, you can mark zero."))

    def __str__(self):
        return str(self.core_number)

    class Meta:
        verbose_name_plural = _('Key Data')


class Comment(models.Model):
    request = models.ForeignKey(Request)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_timestamp = models.DateTimeField(default=now, blank=True)
    message = models.TextField()

    class Meta:
        ordering = ['created_timestamp']

    def __str__(self):
        return str(self.created_timestamp)


class Contact(models.Model):
    buildings = models.ManyToManyField(Building)
    alert_statuses = models.ManyToManyField(Status)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=75, unique=True)


    def __str__(self):
        return self.name


@receiver(pre_save, sender=Request)
def handle(sender, instance, **kwargs):
    request = Request.objects.filter(pk=instance.pk).first()
    if request is not None:
        if instance.status != request.status:
            instance.previous_status = request.status
            instance.updated = False
    else:
        instance.previous_status = instance.status

keyform/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from datetime import datetime, timedelta
from django.views.generic import FormView, UpdateView, View, CreateView
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.db.models import Count, Q
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.utils.timezone import localtime, utc
from django.utils.dateparse import parse_date
from django.utils.translation import ugettext_lazy as _
from keyform.forms import CreateForm, RequestFormSet, EditForm, ContactForm
from keyform.models import Request, Building, Contact, Status


class HomeView(LoginRequiredMixin, ListView):
    template_name = "keyform/home.html"
    paginate_by = 25
    valid_params = ['amt_recieved', 'bpn', 'building__name', 'building_id', 'charge_amount', 'charged_on_rcr',
                    'comment', 'created_timestamp', 'id', 'keydata__room_number', 'keydata__core_number', 'keydata__key_number',
                    'payment_method', 'reason_for_request', 'status__id', 'student_name', 'staff']

    def get_ordering(self):
        self.order = self.request.GET.get('order') or '-created_timestamp'
        return [self.order, '-created_timestamp']

    def get_context_data(self):
        context = super(HomeView, self).get_context_data()
        context["request_types"] = Request.REQUEST_TYPES
        context["status_types"] = Status.objects.all()
        context["buildings"] = Building.objects.all()
        data = self.request.GET.copy()
        for k, v in self.request.GET.items():
            if k not in self.valid_params or not v:
                del data[k]
        data["start_date"] = self.request.GET.get('start_date', '')
        if data["start_date"] == '':
            del data["start_date"]
        data["end_date"] = self.request.GET.get('end_date', '')
        if data["end_date"] == '':
            del data["end_date"]

        context["search_data"] = data
        context["order"] = self.order
        context["order_desc"] = self.order[0] == '-'
        context["order_codename"] = self.order[1:] if context["order_desc"] else self.order
        return context

    def get_date_range(self):
        self.converted_start_date = parse_date(self.request.GET.get('start_date', '')) or datetime.min.replace(tzinfo=utc)
        self.converted_end_date = parse_date(self.request.GET.get('end_date', '')) or datetime.max.replace(tzinfo=utc)

        if self.converted_end_date != datetime.max.replace(tzinfo=utc):
            self.converted_end_date += timedelta(days=1)

    def get_queryset(self):
        self.queryset = Request.active_objects
        if 'status__id' in self.request.GET:
            self.queryset = Request.objects
        qset = super(HomeView, self).get_queryset()
        qset = qset.select_related('building')
        qset = qset.prefetch_related('keydata_set')
        qset = qset.select_related('status')
        qset = qset.annotate(num_comments=Count('comment'))

        for item, value in self.request.GET.items():
            if str(item) in self.valid_params and str(item) != 'staff':
                if value != '':
                    qset = qset.filter(**{item + '__icontains': value})

        self.get_date_range()
        qset = qset.filter(created_timestamp__range=[self.converted_start_date, self.converted_end_date])

        staff_searched = self.request.GET.get('staff', '').split()

        filter_Qs = Q()
        for token in staff_searched:
            or_Qs = Q()
            for field in ['first_name', 'last_name', 'username', 'email']:
                or_Qs |= Q(**{'staff__' + field + '__icontains': token})
            filter_Qs &= or_Qs

        qset = qset.filter(filter_Qs)

        return qset


class RequestView(LoginRequiredMixin, UpdateView):
    model = Request
    success_url = reverse_lazy('home')
    template_name = "keyform/request.html"
    form_class = EditForm
    success_url = reverse_lazy("home")


class RequestCommentView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        message = request.POST['message']
        pk = request.POST['pk']

        req = get_object_or_404(Request, pk=pk)
        comment = req.comment_set.create(message=message, author=request.user)

        timestamp = localtime(comment.created_timestamp).strftime('%B %d, %Y, %I:%M %p')
        return JsonResponse({'author': str(comment.author.get_full_name()), 'timestamp': timestamp, 'message': comment.message})


class ContactView(LoginRequiredMixin, TemplateView):
    template_name = "keyform/contact.html"

    def get_context_data(self):
        context = super(ContactView, self).get_context_data()
        context["buildings"] = Building.objects.all()
        return context

    def post(self, request, *args, **kwargs):

        success = False
        if request.user.has_perm('keyform.delete_contact'):
            pk = request.POST['pk']
            Contact.objects.filter(pk=pk).delete()
            success = True

        return JsonResponse({'success': success})


class EditContactView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = "keyform/contact_form.html"
    model = Contact
    form_class = ContactForm
    success_url = reverse_lazy('contact')
    permission_required = 'keyform.change_contact'
    raise_exception = True

class NewContactView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = "keyform/contact_form.html"
    model = Contact
    form_class = ContactForm
    success_url = reverse_lazy('contact')

    permission_required = 'keyform.add_contact'



    def form_invalid(self, form):
        if list(filter(lambda e: e.code == 'unique', form.errors.as_data().get('email', []))):
            messages.error(self.request, 'Error: This contact already exists, you have been redirected to it.')
            preexisting_contact = Contact.objects.filter(email__iexact=form.instance.email).get()
            return HttpResponseRedirect(reverse('edit-contact', kwargs={'pk': preexisting_contact.pk}))

        return super().form_invalid(form)


class KeyRequest(LoginRequiredMixin, FormView):
    template_name = "keyform/add_form.html"
    success_url = reverse_lazy("home")
    comment_errors = []

    def form_valid(self, form):
        new_request = form.save(commit=False)
        form.request_formset = RequestFormSet(self.request.POST, instance=new_request)
        for request_form in form.request_formset.forms:
            request_form.empty_permitted = False
        if form.request_formset.is_valid() and form.request_formset.has_changed():
            comment_text = self.check_comment(form) # This will generate any self.comment_errors for us
            if self.comment_errors:
                return self.form_invalid(form)
            new_request.save()
            form.request_formset.save()
            if comment_text: # Create the comment AFTER saving new_request
                new_request.comment_set.create(message=comment_text, author=self.request.user)
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.form_invalid(form)

    def form_invalid(self, form):
        # Generate any self.comment_errors
        self.check_comment(form)
        return super(KeyRequest, self).form_invalid(form)

    def check_comment(self, form):
        comment_text = self.request.POST.get('comment_text', '')
        if comment_text.strip():
            return comment_text
        elif form.instance.reason_for_request in ("dk", "sk"):
            self.comment_errors = [_("This field is required.")]
        return ''

    def get_form(self, form_class=None):
        form = CreateForm(instance=Request(staff=self.request.user, status=Status.objects.first()), **self.get_form_kwargs())
        form.request_formset = RequestFormSet(**self.get_form_kwargs())
        return form

    def get_context_data(self, **kwargs):
        context = super(KeyRequest, self).get_context_data(**kwargs)
        if self.request.method == 'POST':
            context['comment_errors'] = self.comment_errors
            context['comment_text'] = self.request.POST.get('comment_text', '')
        return context

keyform/templates/keyform/add_form.html
{% extends "keyform/base.html" %}
{% load static %}
{% load i18n %}

{% block javascript %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'keyform/js/add_form.js' %}"></script>
{% endblock %}
{% block css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'keyform/css/add_form.css' %}"/>
{% endblock %}

{% block content %}
    {{ block.super }}
    <form method=POST>
        {% csrf_token %}
        <div class="row field-wrapper">
            {{ form.non_field_errors }}
            <div class="large-12 columns">
                <div class="row">
                    <div class="large-6 columns">
                        {{ form.reason_for_request.errors }}
                        {{ form.reason_for_request.label_tag }}
                        {{ form.reason_for_request }}
                    </div>
                    <div class="large-6 columns">
                        <label>{% trans 'Submitted by:' %}</label>
                        {{ user.get_full_name }}
                    </div>
                </div>
            </div>
            <div class="large-6 columns">
                {{ form.student_name.errors }}
                {{ form.student_name.label_tag }}
                {{ form.student_name }}
            </div>
            <div class="large-6 columns">
                {{ form.bpn.errors }}
                {{ form.bpn.label_tag }}
                {{ form.bpn }}
            </div>
            <div class="large-6 columns">
                {{ form.request_formset.management_form }}
                {{ form.building.errors }}
                {{ form.building.label_tag }}
                {{ form.building }}
            </div>
            <div class="large-6 columns">
                {{ form.request_formset.empty_form.room_number.label_tag }}
                {{ form.request_formset.empty_form.room_number.errors }}
                {{ form.request_formset.empty_form.room_number }}
            </div>
            <div id="form-set">
                {% for keydata_form in form.request_formset.forms %}
                    {% include 'keyform/includes/keydata_form.html' %}
                {% endfor %}
            </div>
            <div id="empty_form" style="display:none">
                {% include 'keyform/includes/keydata_form.html' with keydata_form=form.request_formset.empty_form %}
            </div>
            <div class="row">
                <div class="large-3 medium-4 columns end">
                    <div class="large-8 medium-8 small-12 columns">
                        {{ form.charge_amount.errors }}
                        {{ form.charge_amount.label_tag }}
                    </div>
                    <div class="large-4 medium-4 small-12 columns">
                        {{ form.charge_amount }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="large-3 medium-4 small-6 columns end">
                    <div class="large-8 medium-8 small-9 columns">
                        {{ form.charged_on_rcr.errors }}
                        {{ form.charged_on_rcr.label_tag }}
                    </div>
                    <div class="large-4 medium-4 small-3 columns">
                        {{ form.charged_on_rcr }}
                    </div>
                </div>
            </div>
            <div class="large-6 columns">
                <div class="row">
                    <div class="large-4 medium-2 small-12 columns">
                        <span class="has-tip help-text" title="{{ form.amt_received.help_text }}">{{ form.amt_received.label_tag }}</span>
                    </div>
                    <div class="large-8 medium-10 small-12 columns">
                        {{ form.amt_received }}
                        {{ form.amt_received.errors }}
                    </div>
                </div>
            </div>
            <div class="large-6 columns">
                <div class="row">
                    <div class="large-4 medium-2 small-12 columns">
                        {{ form.payment_method.errors }}
                        <span class="has-tip help-text" title="{{ form.payment_method.help_text }}">{{ form.payment_method.label_tag }}</span>
                    </div>
                    <div class="large-8 medium-10 small-12 columns">
                        {{ form.payment_method }}
                    </div>
                </div>
            </div>
            <div class="large-12 columns">
                <span class="section-header">{% trans 'Comments:' %}</span>
                {% if comment_errors %}
                    <ul class="errorlist">
                        {% for error in comment_errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <textarea name="comment_text">{{ comment_text }}</textarea>
                <input type="submit"/>
            </div>
        </div>
    </form>
{% endblock %}

keyform/templates/keyform/comment_template.html
<div class="row info-row">
    <div class="large-12 columns end">
        <div class="section-header"><span class='author'>{{ comment.author.get_full_name }}</span> - <span class='timestamp'>{{ comment.created_timestamp|date:'F d, Y, h:i A' }}</span>:</div>
        <p class='message'>{{ comment.message|linebreaksbr }}</p>
    </div>
</div>
<hr width="90%">

keyform/templates/keyform/contact.html
{% extends "keyform/base.html" %}
{% load i18n %}
{% load static %}
{% block css %}
    {{ block.super }}
    <link rel='stylesheet' type='text/css' href="{% static 'keyform/css/contact.css' %}"/>
{% endblock %}
{% block javascript %}
    {{ block.super }}
    <script src='{% static "keyform/js/contact.js" %}'></script>
{% endblock %}

{% block content %}
    {{ block.super }}
    <h2 class='title'>{% trans 'Contacts' %}</h2>
    <div class="contact-container">
        <div class='buildings'>
            {% for building in buildings %}
                <div class="building row">
                    <div class="large-12 columns">
                        <span class="building-name"> {{ building.name }} </span>
                    </div>
                </div>
                {% for contact in building.contact_set.all %}
                    <div class="contact row" data-pk='{{ contact.pk }}'>
                        {% if perms.keyform.change_contact %} <a href='{% url "edit-contact" pk=contact.pk %}'> {% endif %}
                            <div class="info">
                                <div class='large-4 columns'>
                                    <span class='contact-info'>{{ contact.name }}</span>
                                </div>
                                <div class='large-7 columns end'>
                                    <span class='contact-info'>{{ contact.email }}</span>
                                </div>
                            </div>
                        {% if perms.keyform.change_contact %}</a> {% endif %}
                        {% if perms.keyform.delete_contact %}<div class='large-1 columns delete'>X</div> {% endif %}
                    </div>

                {% endfor %}
                {% if perms.keyform.add_contact %}<a href="{% url 'create-contact' %}"><button class='button'>{% trans 'Create Contact' %}</button></a> {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

keyform/templates/keyform/contact_form.html
{% extends 'keyform/base.html' %}
{% load i18n %}
{% load static %}
{% block css %}
    {{ block.super }}
    <link rel='stylesheet' href='{% static "keyform/css/contact_form.css" %}'>
{% endblock %}

{% block content %}
    {{ block.super }}
    <h2 class='title'>{% if form.instance.pk %}{% trans 'Edit Contact' %}{% else %}{% trans 'Create Contact' %}{% endif %}</h2>
    <div class='contact-form'>
        <form method=POST> {% csrf_token %}
            {{ form }}
            <button type='submit' class='button'>{% trans 'Submit' %}</button>
        </form>
    </div>
{% endblock %}

keyform/templates/keyform/request.html
{% extends "keyform/base.html" %}
{% load i18n %}
{% load static %}
{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href = "{% static 'keyform/css/request.css' %}"/>
{% endblock %}
{% block javascript %}
    {{ block.super }}
    <script src="{% static 'keyform/js/request.js' %}"></script>
    <script>
        var COMMENT_URL = "{% url 'add-comment' %}";
        var COMMENT_HTML = "{% filter escapejs %}{% include 'keyform/comment_template.html' %}{% endfilter %}";
    </script>
{% endblock %}

{% block content %}
    {{ block.super }}
    <div class="content">
        <div class="content-header hide-for-print">{% trans 'Update Key Request' %}</div>
        <div class="info">
            <div class="row">
                <div class="small-6 columns">
                    <span class='created'> {% trans 'Created' %}: {{ object.created_timestamp }}</span>
                </div>
                <div class="small-6 columns text-right">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="request-edit">
                            {% for field in form %}
                                {{ field.label }}: {{ field }}
                            {% endfor %}
                            <input type="submit" value="{% trans 'Update' %}" class="hide-for-print"/>
                        </div>
                    </form>
                </div>
            </div>
            <div class="row">
                <div class="medium-7 small-7 columns">
                    <div class="section" id="key-section" data-pk="{{ object.pk }}">
                        <div class="row info-row">
                             <div class="large-12 columns">
                                 <span class="section-header">{% trans 'Basic Info' %}</span>
                             </div>
                             <div class="large-7 columns">
                                 {% trans 'Student Name' %}: <span class="section-info">{{ object.student_name }}</span>
                             </div>
                             <div class="large-5 columns">
                                 {% trans 'Request For' %}: <span class="section-info">{{ object.get_reason_for_request_display }}</span>
                             </div>
                        </div>
                        <div class="row info-row">
                            <div class="large-12 columns">
                                {% trans 'Building Name' %}: <span class="section-info">{{ object.building }}</span>
                            </div>
                        </div>
                        <div class="row info-row">
                            <div class="large-7 columns">
                                {% trans 'Amount Received' %}: <span class="section-info">{{ object.amt_received }}</span>
                            </div>
                            <div class="large-5 columns">
                                {% trans 'Paid By' %}: <span class="section-info">{{ object.get_payment_method_display }}</span>
                            </div>
                        </div>
                        <div class="row info-row">
                            <div class="large-7 columns">
                                {% trans 'Bill to Account' %}: <span class="section-info">{{ object.charge_amount }}</span>
                            </div>
                            <div class="large-5 columns">
                                {% trans 'M-Number' %}: <span class="section-info">{{ object.bpn }}</span>
                            </div>
                        </div>
                        <div class="row info-row">
                            <div class="large-7 columns">
                                {% trans 'Submitted By' %}: <span class="section-info">{{ object.staff.get_full_name }}</span>
                            </div>
                            <div class="large-5 columns">
                                {% trans 'Charged on RCR' %}: {% if object.charged_on_rcr %} <i class="fa fa-check section-info" aria-hidden="true"> {% trans 'Yes' %}</i> {% else %} <i class="fa fa-times section-info" aria-hidden="true"> {% trans 'No' %}</i> {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="medium-5 small-5 columns">
                    <div class="section">
                        <div class="row info-row">
                            <div class="large-12 columns">
                                <span class="section-header">{% trans 'Keydata' %}</span>
                            </div>
                        </div>
                        {% for data in object.keydata_set.all %}
                            <div class="row info-row">
                                {% if not data.key_type.hide_core_number %}
                                    <div class="large-4 columns">{% trans 'New Core #' %}: <span class="section-info">{{ data.core_number }}</span></div>
                                {% endif %}
                                <div class="large-4 columns">{% trans 'Room #' %}: <span class="section-info">{{ data.room_number }}</span></div>
                                <div class="large-4 columns">{% trans 'Lost/Stolen/Damaged Key #' %}: <span class="section-info">{{ data.key_number }}</span></div>
                            </div>
                            <div class="row info-row">
                                <div class="large-8 columns">{% trans 'Key Type' %}: <span class="section-info">{{ data.key_type }}</span></div>
                                <div class="large-4 columns">{% trans 'Quantity' %}: <span class="section-info">{{ data.quantity }}</span></div>
                            </div>
                            {% if not forloop.last %}<hr width="80%">{% endif %}
                        {% endfor %}
                    </div>
                </div>
            <br>
        </div>
        <div class="row">
            <div id="comments" class="section">
                {% with comments=object.comment_set.all %}
                    <span class="section-header">{% trans 'Comments' %} </span>
                    <div id="comment-list">
                        {% for comment in comments %}
                            {% include 'keyform/comment_template.html' %}
                        {% endfor %}
                    </div>
                {% endwith %}
                <div id="comment-form">
                    <div class="hide-for-print">
                        <p>{% trans 'New Comment:' %}</p>
                        <textarea id="comment-text" cols="40" rows="4"></textarea>
                        <span class='button small' type='button' id='submit'>{% trans 'Submit' %}</span>
                        <span class='button small' type='button' id='cancel'>{% trans 'Cancel' %}</span>
                    </div>
                </div>
                <div class="hide-for-print">
                    <span class="button small" type="button" id="add">{% trans 'Add a comment' %}</span>
                </div>
            </div>
        </div>
    </div>
{% endblock %}